apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: tsyjggqbc-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/tsyjggqbc-java-quarkus-gitops